# Workflow for deploying Jekyll with GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Trigger workflow on push to the "mainster" branch or manual dispatch
  push:
    branches: ["mainster"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Build with Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # Debug the _site directory
      - name: Debug Output
        run: ls -R ./_site

      # Rename booksSearch.html to index.html
      - name: Rename booksSearch.html to index.html
        run: mv "./_site/Book Nook/booksSearch.html" "./_site/index.html"

      # Upload the artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
